-- =====================================================================
-- 005 — دفتر الأستاذ والترتيب الزمني الحاسم (Running Ledger)
-- يُنفَّذ بعد 004_performance.sql
-- ✅ Idempotent: يمكن إعادة تشغيله بأمان أكثر من مرة
-- ✅ آمن على البيانات الموجودة
--
-- الهدف الهندسي:
-- 1) عمود seq رتيب (Identity Sequence) يعطي ترتيب إدراج حاسماً حتى عند
--    عمليتين بنفس الطابع الزمني (نفس الثانية) — فلا تتناوب النتائج ولا
--    يُقلب «آخر عملية» في /undo.
-- 2) View دفتر الأستاذ v_customer_ledger: حركات كل عميل تصاعدياً مع
--    الرصيد التراكمي (Running Balance) بعد كل حركة — أساس كشف الحساب
--    الجاري، محسوباً بدقة numeric(15,2) على مستوى قاعدة البيانات.
-- =====================================================================

begin;

-- ═══════════════════════════════════════════════════════════════
-- 1) عمود الترتيب الرتيب seq
-- ═══════════════════════════════════════════════════════════════
alter table public.transactions
    add column if not exists seq bigint generated by default as identity;

comment on column public.transactions.seq
    is 'رقم تسلسلي رتيب يعكس ترتيب الإدراج الفعلي — حاسم عند تساوي created_at';

-- فهرس خدمة الترتيب الزمني (الأقدم أولاً) لدفتر الأستاذ
create index if not exists idx_transactions_customer_seq
    on public.transactions (customer_id, created_at asc, seq asc);

-- ═══════════════════════════════════════════════════════════════
-- 2) View دفتر الأستاذ مع الرصيد التراكمي
-- ═══════════════════════════════════════════════════════════════
drop view if exists public.v_customer_ledger;

create or replace view public.v_customer_ledger as
select
    t.customer_id,
    t.id,
    t.amount,
    t.tx_type,
    t.note,
    t.created_at,
    t.seq,
    sum(t.amount) over (
        partition by t.customer_id
        order by t.created_at, t.seq
        rows between unbounded preceding and current row
    )::numeric(15, 2) as running_balance
from public.transactions t;

comment on view public.v_customer_ledger
    is 'دفتر الأستاذ: حركات كل عميل بالترتيب الزمني الحاسم (created_at, seq) مع الرصيد التراكمي بعد كل حركة';

grant select on public.v_customer_ledger to service_role;

commit;