-- ═══════════════════════════════════════════════════════════════════
--  master_schema.sql — المخطط الرئيسي الموحّد لمشروع بوت الديون والوقود
--  نسخة: 1.0 (تاريخ التوحيد: 2026-09-02)
--
--  دمج مطهَّر لستة ملفات هجرة: 001 → 006، مرتّباً هندسياً:
--    §0  الامتدادات
--    §1  الجداول الأساسية (بأشكالها النهائية الكاملة + القيود المسمّاة)
--    §2  تمريرة توافق لقواعد بيانات قديمة (كلها no-op على قاعدة جديدة)
--    §3  الدوال (Triggers Infrastructure + RPC)
--    §4  ربط الـ Triggers
--    §5  الفهارس (المجموعة النهائية بعد إزالة المكرر)
--    §6  الـ Views (النسخة النهائية الوحيدة لكل واحدة)
--    §7  RLS + الامتيازات
--
--  ✅ Idempotent: يُعاد تشغيله بأمان على نفس القاعدة
--  ✅ آمن: يُنشأ من صفحة بيضاء أو يُطبَّق فوق قاعدة قائمة دون إتلاف
--  ✅ ذرّي: الملف كله داخل معاملة واحدة — نجاح كامل أو تراجع كامل
--
--  ملاحظات التطهير (ما تغيّر عن الملفات القديمة):
--   • حُذف idx_transactions_created_at (مكرر مطابق لـ idx_transactions_created)
--   • حُذف idx_transactions_tx_type_created (مكرر مطابق لـ idx_transactions_type_created)
--   • حُذف idx_customers_name_normalized (زائد عن فهرس قيد UNIQUE التلقائي)
--   • v_customer_balances كانت تُعرَّف 3 مرات (001/002/003) — تُنشأ هنا مرة واحدة بالنسخة النهائية
--   • أُضيف منح USAGE على sequence عمود seq (كان مفقوداً في 005)
-- ═══════════════════════════════════════════════════════════════════

begin;

-- ═══════════════════════════════════════════════════════════════════
-- §0) الامتدادات
-- ═══════════════════════════════════════════════════════════════════
create extension if not exists pgcrypto;

-- ═══════════════════════════════════════════════════════════════════
-- §1) الجداول الأساسية — الأشكال النهائية الكاملة
-- ═══════════════════════════════════════════════════════════════════

-- ── 1.1) العملاء ──────────────────────────────────────────────────
create table if not exists public.customers (
    id               uuid primary key default gen_random_uuid(),
    name             text not null,
    name_normalized  text not null unique,
    last_activity_at timestamptz,
    created_at       timestamptz not null default now(),
    updated_at       timestamptz not null default now(),
    constraint ck_customers_name_not_blank       check (btrim(name) <> ''),
    constraint ck_customers_normalized_not_blank check (btrim(name_normalized) <> '')
);

comment on table public.customers is 'عملاء المحطة — يُنشأ الحساب تلقائياً عند أول ذكر للاسم';
comment on column public.customers.name_normalized
    is 'الاسم بعد التطبيع الصارم (أ/إ/آ←ا، ة←ه، ى←ي، ؤ/ئ←ء) لمنع أي تكرار';
comment on column public.customers.last_activity_at
    is 'آخر لحظة تم فيها أي معاملة للعميل — أساس التنبيه الأسبوعي لغير النشطين';
comment on column public.customers.updated_at
    is 'آخر تعديل على سجل العميل (يُحدَّث تلقائياً عبر trigger)';

-- ── 1.2) حركات النقد (الديون والسداديات) ─────────────────────────
create table if not exists public.transactions (
    id           uuid primary key default gen_random_uuid(),
    customer_id  uuid not null
        references public.customers (id) on delete restrict,
    amount       numeric(15,2) not null check (amount <> 0),
    tx_type      text not null check (tx_type in ('debit', 'credit')),
    note         text,
    external_ref text,
    seq          bigint generated by default as identity,
    created_at   timestamptz not null default now(),
    updated_at   timestamptz not null default now(),
    -- القيد الذهبي: الإشارة تطابق الاتجاه دائماً
    constraint ck_transactions_sign check (
        (tx_type = 'debit'  and amount > 0)
     or (tx_type = 'credit' and amount < 0)
    ),
    -- منع تسجيل الحركة مرتين ذرّياً (Idempotency)
    constraint ux_transactions_external_ref unique (external_ref),
    constraint ck_transactions_note_len check (note is null or char_length(note) <= 500)
);

comment on column public.transactions.amount is 'دين موجبة (+)، سداد سالبة (−) — دائماً numeric(15,2)';
comment on column public.transactions.external_ref
    is 'مرجع خارجي اختياري (رقم وصل/فاتورة) بهدف منع تسجيل الحركة مرتين';
comment on column public.transactions.seq
    is 'رقم تسلسلي رتيب يعكس ترتيب الإدراج الفعلي — حاسم عند تساوي created_at';
comment on column public.transactions.updated_at
    is 'علامة تغيير على حركة مالية — أي تعديل يُسجَّل في audit_log معاً';

-- ── 1.3) المحاسبي الشخصي للمالك ──────────────────────────────────
create table if not exists public.account_entries (
    id         uuid primary key default gen_random_uuid(),
    entry_type text not null check (entry_type in ('income', 'expense')),
    amount     numeric(15,2) not null,
    note       text,
    category   text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ck_account_entries_amount_positive check (amount > 0),
    constraint ck_account_entries_note_len     check (note is null or char_length(note) <= 200),
    constraint ck_account_entries_category_len check (category is null or char_length(category) <= 50)
);

comment on table public.account_entries
    is 'المحاسبي الشخصي للمالك: income (دخل) و expense (مصروف) — لا علاقة بديون العملاء';
comment on column public.account_entries.amount
    is 'مبلغ موجب دائماً، والاتجاه في entry_type — numeric(15,2)';

-- ── 1.4) إعدادات التطبيق الديناميكية ─────────────────────────────
create table if not exists public.app_settings (
    key        text primary key,
    value      text not null,
    updated_at timestamptz not null default now(),
    constraint ck_app_settings_inactive_days check (key <> 'inactive_days' or value ~ '^[0-9]{1,4}$'),
    constraint ck_app_settings_weekday       check (key <> 'weekly_alert_weekday' or value ~ '^[0-6]$'),
    constraint ck_app_settings_time
        check (key <> 'weekly_alert_time' or value ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
    constraint ck_app_settings_enabled
        check (key <> 'weekly_alert_enabled' or value in ('0', '1', 'true', 'false')),
    constraint ck_app_settings_value_len check (char_length(value) <= 500)
);

comment on table public.app_settings
    is 'إعدادات التشغيل الديناميكية التي تُضبط من داخل البوت (/alerts)';

insert into public.app_settings (key, value) values
    ('inactive_days', '30'),
    ('weekly_alert_enabled', '1'),
    ('weekly_alert_weekday', '6'),
    ('weekly_alert_time', '09:00')
on conflict (key) do nothing;

-- ── 1.5) دفتر لترات الوقود — حساب كمّي مستقل عن النقد تماماً ────
create table if not exists public.fuel_ledger (
    id           uuid primary key default gen_random_uuid(),
    customer_id  uuid not null
        references public.customers (id) on delete restrict,
    fuel_type    text not null check (fuel_type in ('mazot', 'benzine')),
    liters       numeric(15,3) not null,
    entry_type   text not null check (entry_type in ('debit', 'credit')),
    note         text,
    external_ref text,
    created_at   timestamptz not null default now(),
    updated_at   timestamptz not null default now(),
    -- القيد الذهبي: إشارة اللترات تطابق الاتجاه (سحب «+» / إيداع «−»)
    constraint ck_fuel_liters_sign check (
        (entry_type = 'debit'  and liters > 0)
     or (entry_type = 'credit' and liters < 0)
    ),
    -- منع تكرار الإدراج ذرّياً (Idempotency) — يُستخدم من التطبيق
    constraint ux_fuel_ledger_external_ref unique (external_ref)
);

comment on table public.fuel_ledger
    is 'دفتر لترات الوقود المستقل: سحب/إيداع مازوت وبنزين كقيمة كمّية — منفصل تماماً عن رصيد النقد';
comment on column public.fuel_ledger.liters
    is 'لترات الوقود: سحب (دين) «+» / إيداع (سداد) «−» — numeric(15,3) لدعم أجزاء اللتر';
comment on column public.fuel_ledger.fuel_type is 'نوع الوقود: mazot (مازوت) أو benzine (بنزين)';

-- ── 1.6) سجل التدقيق المظلم ─────────────────────────────────────
create table if not exists public.audit_log (
    id         bigint generated always as identity primary key,
    table_name text not null,
    operation  text not null check (operation in ('INSERT', 'UPDATE', 'DELETE')),
    record_id  uuid,
    old_data   jsonb,
    new_data   jsonb,
    done_by    text,
    changed_at timestamptz not null default now()
);

comment on table public.audit_log
    is 'سجل التدقيق المظلم — كل تغيير على البيانات المالية يُسجَّل هنا تلقائياً ولا يُحذف عبر التطبيق';

-- ═══════════════════════════════════════════════════════════════════
-- §2) تمريرة التوافق — لقواعد بيانات قديمة أُنشئت قبل التوحيد
--     على قاعدة بيضاء جديدة كل ما يلي no-op لا يؤثر على شيء.
-- ═══════════════════════════════════════════════════════════════════

-- 2.1) ضمان وجود كل الأعمدة المضافة لاحقاً في الملفات القديمة
alter table public.customers    add column if not exists last_activity_at timestamptz;
alter table public.customers    add column if not exists updated_at       timestamptz;
alter table public.transactions add column if not exists updated_at       timestamptz;
alter table public.transactions add column if not exists external_ref     text;
alter table public.transactions add column if not exists seq
    bigint generated by default as identity;
alter table public.account_entries add column if not exists updated_at    timestamptz;
alter table public.app_settings    add column if not exists updated_at    timestamptz;

-- 2.2) ردم القيم السابقة ثم تثبيت NOT NULL (نفس تسلسل 003 الآمن)
update public.customers
   set updated_at = coalesce(last_activity_at, created_at)
 where updated_at is null;
update public.transactions
   set updated_at = created_at
 where updated_at is null;
update public.account_entries
   set updated_at = created_at
 where updated_at is null;
update public.app_settings
   set updated_at = now()
 where updated_at is null;

alter table public.customers       alter column updated_at set default now();
alter table public.transactions    alter column updated_at set default now();

-- 2.3) القيود المسمّاة — تُضاف فقط إن كانت الجداول قائمة سابقاً بلا هذه القيود
do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'ck_transactions_sign'
          and conrelid = 'public.transactions'::regclass
    ) then
        alter table public.transactions
            add constraint ck_transactions_sign check (
                (tx_type = 'debit'  and amount > 0)
             or (tx_type = 'credit' and amount < 0)
            );
    end if;
end;
$$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'ux_transactions_external_ref'
          and conrelid = 'public.transactions'::regclass
    ) then
        alter table public.transactions
            add constraint ux_transactions_external_ref unique (external_ref);
    end if;
end;
$$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'ck_customers_name_not_blank'
          and conrelid = 'public.customers'::regclass
    ) then
        alter table public.customers
            add constraint ck_customers_name_not_blank check (btrim(name) <> '');
    end if;
end;
$$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'ck_customers_normalized_not_blank'
          and conrelid = 'public.customers'::regclass
    ) then
        alter table public.customers
            add constraint ck_customers_normalized_not_blank check (btrim(name_normalized) <> '');
    end if;
end;
$$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'ck_transactions_note_len'
          and conrelid = 'public.transactions'::regclass
    ) then
        alter table public.transactions
            add constraint ck_transactions_note_len check (note is null or char_length(note) <= 500);
    end if;
end;
$$;

alter table public.account_entries alter column updated_at set default now();
alter table public.app_settings    alter column updated_at set default now();

alter table public.customers       alter column updated_at set not null;
alter table public.transactions    alter column updated_at set not null;
alter table public.account_entries alter column updated_at set not null;
alter table public.app_settings    alter column updated_at set not null;


do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'ck_account_entries_note_len'
          and conrelid = 'public.account_entries'::regclass
    ) then
        alter table public.account_entries
            add constraint ck_account_entries_note_len check (note is null or char_length(note) <= 200);
    end if;
end;
$$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'ck_account_entries_category_len'
          and conrelid = 'public.account_entries'::regclass
    ) then
        alter table public.account_entries
            add constraint ck_account_entries_category_len
            check (category is null or char_length(category) <= 50);
    end if;
end;
$$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'ck_account_entries_amount_positive'
          and conrelid = 'public.account_entries'::regclass
    ) then
        alter table public.account_entries
            add constraint ck_account_entries_amount_positive check (amount > 0);
    end if;
end;
$$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'ck_app_settings_inactive_days'
          and conrelid = 'public.app_settings'::regclass
    ) then
        alter table public.app_settings
            add constraint ck_app_settings_inactive_days
            check (key <> 'inactive_days' or value ~ '^[0-9]{1,4}$');
    end if;
end;
$$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'ck_app_settings_weekday'
          and conrelid = 'public.app_settings'::regclass
    ) then
        alter table public.app_settings
            add constraint ck_app_settings_weekday
            check (key <> 'weekly_alert_weekday' or value ~ '^[0-6]$');
    end if;
end;
$$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'ck_app_settings_time'
          and conrelid = 'public.app_settings'::regclass
    ) then
        alter table public.app_settings
            add constraint ck_app_settings_time
            check (key <> 'weekly_alert_time' or value ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$');
    end if;
end;
$$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'ck_app_settings_enabled'
          and conrelid = 'public.app_settings'::regclass
    ) then
        alter table public.app_settings
            add constraint ck_app_settings_enabled
            check (key <> 'weekly_alert_enabled' or value in ('0', '1', 'true', 'false'));
    end if;
end;
$$;

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'ck_app_settings_value_len'
          and conrelid = 'public.app_settings'::regclass
    ) then
        alter table public.app_settings
            add constraint ck_app_settings_value_len check (char_length(value) <= 500);
    end if;
end;
$$;

-- ═══════════════════════════════════════════════════════════════════
-- §3) الدوال (Triggers Infrastructure + RPC)
-- ═══════════════════════════════════════════════════════════════════

-- 3.1) ختم updated_at تلقائياً
create or replace function public.fn_set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

-- 3.2) لمس last_activity_at عند إدراج حركة نقدية
create or replace function public.fn_touch_last_activity()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    update public.customers c
       set last_activity_at = greatest(c.last_activity_at, new.created_at)
     where c.id = new.customer_id
       and (c.last_activity_at is null or c.last_activity_at < new.created_at);
    return new;
end;
$$;

-- 3.3) إعادة حساب last_activity_at بعد حذف حركة نقدية (دقة /undo)
create or replace function public.fn_recalc_last_activity()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    update public.customers c
       set last_activity_at = (
           select max(t.created_at)
             from public.transactions t
            where t.customer_id = c.id
       )
     where c.id = old.customer_id;
    return old;
end;
$$;

-- 3.4) سجل التدقيق المظلم
create or replace function public.fn_audit_log()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_new jsonb := null;
    v_old jsonb := null;
    v_id  uuid  := null;
begin
    if tg_op in ('INSERT', 'UPDATE') then
        v_new := to_jsonb(new);
        v_id  := new.id;
    end if;

    if tg_op in ('UPDATE', 'DELETE') then
        v_old := to_jsonb(old);
        if tg_op = 'DELETE' then
            v_id := old.id;
        end if;
    end if;

    insert into public.audit_log (table_name, operation, record_id, old_data, new_data, done_by)
    values (tg_table_name, tg_op, v_id, v_old, v_new, session_user::text);

    return coalesce(new, old);
end;
$$;

-- 3.5) RPC: رصيد عميل واحد (PostgREST)
create or replace function public.fn_customer_balance(p_customer_id uuid)
returns numeric(15, 2)
language sql
stable
parallel safe
set search_path = ''
as $$
    select coalesce(sum(t.amount), 0)::numeric(15, 2)
      from public.transactions t
     where t.customer_id = p_customer_id;
$$;


-- ═══════════════════════════════════════════════════════════════════
-- §4) ربط الـ Triggers بالجداول
-- ═══════════════════════════════════════════════════════════════════

-- 4.1) ختم updated_at
drop trigger if exists trg_customers_updated_at on public.customers;
create trigger trg_customers_updated_at
    before update on public.customers
    for each row execute function public.fn_set_updated_at();

drop trigger if exists trg_transactions_updated_at on public.transactions;
create trigger trg_transactions_updated_at
    before update on public.transactions
    for each row execute function public.fn_set_updated_at();

drop trigger if exists trg_account_entries_updated_at on public.account_entries;
create trigger trg_account_entries_updated_at
    before update on public.account_entries
    for each row execute function public.fn_set_updated_at();

drop trigger if exists trg_app_settings_updated_at on public.app_settings;
create trigger trg_app_settings_updated_at
    before update on public.app_settings
    for each row execute function public.fn_set_updated_at();

drop trigger if exists trg_fuel_ledger_updated_at on public.fuel_ledger;
create trigger trg_fuel_ledger_updated_at
    before update on public.fuel_ledger
    for each row execute function public.fn_set_updated_at();

-- 4.2) تتبع آخر نشاط للعميل (إدراج/حذف حركة نقدية)
drop trigger if exists trg_txn_touch_customer on public.transactions;
create trigger trg_txn_touch_customer
    after insert on public.transactions
    for each row execute function public.fn_touch_last_activity();

drop trigger if exists trg_txn_recalc_customer on public.transactions;
create trigger trg_txn_recalc_customer
    after delete on public.transactions
    for each row execute function public.fn_recalc_last_activity();

-- 4.3) سجل التدقيق
drop trigger if exists trg_audit_customers on public.customers;
create trigger trg_audit_customers
    after insert or update or delete on public.customers
    for each row execute function public.fn_audit_log();

drop trigger if exists trg_audit_transactions on public.transactions;
create trigger trg_audit_transactions
    after insert or update or delete on public.transactions
    for each row execute function public.fn_audit_log();

drop trigger if exists trg_audit_account_entries on public.account_entries;
create trigger trg_audit_account_entries
    after insert or update or delete on public.account_entries
    for each row execute function public.fn_audit_log();

drop trigger if exists trg_audit_fuel_ledger on public.fuel_ledger;
create trigger trg_audit_fuel_ledger
    after insert or update or delete on public.fuel_ledger
    for each row execute function public.fn_audit_log();

-- ═══════════════════════════════════════════════════════════════════
-- §5) الفهارس — المجموعة النهائية بعد إزالة المكرر
--     مبنية على أنماط استعلام البوت الفعلية فقط
-- ═══════════════════════════════════════════════════════════════════

-- حركات العميل: كشف/نشاط/سجل — الترتيب الحاسم (created_at, id)
create index if not exists idx_transactions_customer_created
    on public.transactions (customer_id, created_at desc, id desc);

-- دفتر الأستاذ التراكمي: الترتيب التصاعدي الحاسم (created_at, seq)
create index if not exists idx_transactions_customer_seq
    on public.transactions (customer_id, created_at asc, seq asc);

-- عمليات اليوم / آخر النشاط على مستوى النظام
create index if not exists idx_transactions_created
    on public.transactions (created_at desc);

-- آخر السداديات / الديون بحسب النوع
create index if not exists idx_transactions_type_created
    on public.transactions (tx_type, created_at desc);

-- حارس منع التكرار: (العميل + المبلغ + النوع + الوقت) — استعلام فوري
create index if not exists idx_transactions_dedup
    on public.transactions (customer_id, amount, tx_type, created_at desc);

-- فهرس سريع للحسابات المحاسبية (النوع + المبلغ + الوقت)
create index if not exists idx_account_entries_dedup
    on public.account_entries (entry_type, amount, created_at desc);

-- تصفية المحاسبي الشخصي حسب التصنيف
create index if not exists idx_account_entries_category_created
    on public.account_entries (category, created_at desc);

-- تنبيه الحسابات غير النشطة
create index if not exists idx_customers_last_activity
    on public.customers (last_activity_at);

-- كشف حساب الوقود لكل عميل بالترتيب الحاسم
create index if not exists idx_fuel_ledger_customer_created
    on public.fuel_ledger (customer_id, fuel_type, created_at desc, id desc);

-- أرصدة الوقود بحسب النوع
create index if not exists idx_fuel_ledger_type_liters
    on public.fuel_ledger (fuel_type, liters, created_at desc);

-- سجل التدقيق: بحث بحسب الكيان ثم بحسب الزمن
create index if not exists idx_audit_log_entity
    on public.audit_log (table_name, record_id, changed_at desc);
create index if not exists idx_audit_log_changed
    on public.audit_log (changed_at desc);


-- ═══════════════════════════════════════════════════════════════════
-- §6) الـ Views — النسخة النهائية الوحيدة لكل واحدة
-- ═══════════════════════════════════════════════════════════════════

-- 6.1) دفتر الأستاذ التراكمي: حركات كل عميل بالترتيب الزمني الحاسم
--      (created_at, seq) مع الرصيد التراكمي بعد كل حركة — numeric(15,2)
drop view if exists public.v_customer_ledger;
create or replace view public.v_customer_ledger as
select
    t.customer_id,
    t.id,
    t.amount,
    t.tx_type,
    t.note,
    t.created_at,
    t.seq,
    sum(t.amount) over (
        partition by t.customer_id
        order by t.created_at, t.seq
        rows between unbounded preceding and current row
    )::numeric(15, 2) as running_balance
from public.transactions t;

comment on view public.v_customer_ledger
    is 'دفتر الأستاذ: حركات كل عميل بالترتيب الزمني الحاسم (created_at, seq) مع الرصيد التراكمي بعد كل حركة';

-- 6.2) الأرصدة النقدية الحية للعملاء
drop view if exists public.v_customer_balances;
create or replace view public.v_customer_balances as
select
    c.id,
    c.name,
    c.name_normalized,
    coalesce(sum(t.amount), 0)::numeric(15, 2) as balance,
    count(t.id)::bigint                          as txn_count,
    max(t.created_at)                            as last_txn_at,
    c.last_activity_at,
    c.created_at,
    c.updated_at,
    case
        when coalesce(sum(t.amount), 0) > 0 then 'debtor'
        when coalesce(sum(t.amount), 0) < 0 then 'creditor'
        else 'settled'
    end as status
from public.customers c
left join public.transactions t on t.customer_id = c.id
group by
    c.id, c.name, c.name_normalized,
    c.last_activity_at, c.created_at, c.updated_at
order by c.name;

comment on view public.v_customer_balances
    is 'الأرصدة الحية للعملاء: debtor (مدين) / creditor (دائن) / settled (مسدَّد)';

-- 6.3) الملخص اليومي للحركات النقدية
drop view if exists public.v_daily_summary;
create view public.v_daily_summary as
select
    date_trunc('day', created_at)::date as day,
    count(*)::bigint                     as txn_count,
    count(*) filter (where tx_type = 'debit')::bigint  as debit_count,
    coalesce(sum(amount) filter (where tx_type = 'debit'), 0)::numeric(15, 2) as debit_total,
    count(*) filter (where tx_type = 'credit')::bigint as credit_count,
    coalesce(sum(-amount) filter (where tx_type = 'credit'), 0)::numeric(15, 2) as credit_total,
    coalesce(sum(amount), 0)::numeric(15, 2) as net_change
from public.transactions
group by 1
order by 1 desc;

-- 6.4) إجماليات النظام
drop view if exists public.v_financial_totals;
create view public.v_financial_totals as
select
    (select count(*)::bigint from public.customers) as customers,
    (select count(*)::bigint from public.transactions) as transactions,
    (select coalesce(sum(amount), 0)::numeric(15, 2) from public.transactions) as total_balance,
    (select coalesce(sum(amount), 0)::numeric(15, 2) from public.transactions where amount > 0) as total_debts,
    (select coalesce(sum(-amount), 0)::numeric(15, 2) from public.transactions where amount < 0) as total_paid,
    (select coalesce(sum(case when entry_type = 'income' then amount else -amount end), 0)::numeric(15, 2)
       from public.account_entries) as account_balance;


-- 6.5) إجماليات الصندوق المحاسبي الشخصي — طلب واحد بدل جلب كل القيود
drop view if exists public.v_account_totals;
create view public.v_account_totals as
select
    coalesce(sum(amount) filter (where entry_type = 'income'), 0)::numeric(15, 2)  as income_total,
    coalesce(sum(amount) filter (where entry_type = 'expense'), 0)::numeric(15, 2) as expense_total,
    coalesce(sum(case when entry_type = 'income' then amount else -amount end), 0)::numeric(15,2) as balance
from public.account_entries;

comment on view public.v_account_totals
    is 'إجماليات الصندوق الشخصي في طلب واحد: دخل / مصروف / الرصيد الصافي';

-- 6.6) أرصدة وقود العملاء — معزولة تماماً عن الأرصدة النقدية
drop view if exists public.v_fuel_balances;
create or replace view public.v_fuel_balances as
select
    c.id,
    c.name,
    c.name_normalized,
    coalesce(sum(f.liters) filter (where f.fuel_type = 'mazot'), 0)::numeric(15, 3)   as mazot_balance,
    coalesce(sum(f.liters) filter (where f.fuel_type = 'benzine'), 0)::numeric(15, 3) as benzine_balance,
    count(f.id)::integer as fuel_txn_count,
    max(f.created_at) as last_fuel_at
from public.customers c
left join public.fuel_ledger f on f.customer_id = c.id
group by c.id, c.name, c.name_normalized
order by c.name;

comment on view public.v_fuel_balances
    is 'أرصدة وقود العملاء معزولة تماماً: مازوت/بنزين باللترات — منفصلة عن v_customer_balances النقدية';

-- ═══════════════════════════════════════════════════════════════════
-- §7) RLS مقفول تماماً + الامتيازات
-- ═══════════════════════════════════════════════════════════════════
alter table public.customers       enable row level security;
alter table public.transactions    enable row level security;
alter table public.account_entries enable row level security;
alter table public.app_settings    enable row level security;
alter table public.fuel_ledger     enable row level security;
alter table public.audit_log       enable row level security;

revoke all on table public.customers, public.transactions,
              public.account_entries, public.app_settings,
              public.fuel_ledger, public.audit_log
      from anon, authenticated;

grant select, insert, update, delete
    on public.customers, public.transactions,
       public.account_entries, public.app_settings,
       public.fuel_ledger
    to service_role;

grant select, insert
    on public.audit_log
    to service_role;

-- sequences الأعمدة الرتيبة (تسلسل الإدراج وسجل التدقيق)
grant usage, select on sequence public.transactions_seq_seq to service_role;
grant usage, select on sequence public.audit_log_id_seq to service_role;

grant select on public.v_customer_balances, public.v_daily_summary,
                public.v_financial_totals, public.v_account_totals,
                public.v_customer_ledger, public.v_fuel_balances
    to service_role;

revoke all on function public.fn_customer_balance(uuid) from public;
grant execute on function public.fn_customer_balance(uuid) to service_role;

revoke all on function public.fn_set_updated_at(),
                public.fn_touch_last_activity(),
                public.fn_recalc_last_activity(),
                public.fn_audit_log()
    from public;

commit;

-- ═══════════════════════════════════════════════════════════════════
-- ✅ اكتمل المخطط الموحد — قاعدة بيانات مدرعة وصاروخية من الضربة الأولى
-- ═══════════════════════════════════════════════════════════════════

